name: 'Staging: Deploy Gateway Server'

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - 'gateway/**'
      - 'gateway-server/**'
      - '.github/workflows/deploy.yml'
      - '.github/workflows/deploy-gateway-server-staging.yaml'

concurrency: gateway_server_staging

jobs:
  deploy:
    if: github.repository == 'WingRiders/wallet' # Perform execution only in the public repo
    uses: ./.github/workflows/deploy.yml
    with:
      environment: preprod
      service: wallet-gateway-server
      deploy: true
      working_directory: .
      dockerfile: gateway-server/Dockerfile
    secrets:
      aws-region: ${{ secrets.AWS_REGION }}
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
